<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo CONFIG_SITE_TITLE ?></title>
    <link  rel="stylesheet" href="./src/App/Assets/css/main.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<!-- HEADER -->
<header>
<nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
    <div class="container-fluid">
    <a class="navbar-brand" href="?page=home">
          <img src="./src/App/Assets/img/3151589_bubble_chat_geek_message_icon.png" alt="Logo Geek" id="logo">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page'] ==='home') echo "active"; ?>" aria-current="page" href="?page=home">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page'] ==='gallery') echo "active"; ?>"  aria-current="page" href="?page=gallery">Gallery</a>
            </li>
            <li class="nav-item">
                <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page'] ==='contact') echo "active"; ?>" aria-current="page" href="?page=contact">Contact</a>
            </li> 
            <?php if(isset( $_SESSION['user'])) : ?>
            <li class="nav-item">
                <a class="nav-link <?php if(isset($_GET['page']) && $_GET['page'] ==='profil') echo "active"; ?>" aria-current="page" href="?page=profil&id=<?= $_SESSION['user']['id'] ?>">Profil</a>
            </li> 
            <?php endif; ?>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Account
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <?php if ($auth::isRole("ROLE_ADMIN")) : ?>
                  <li><a class="dropdown-item" href="?page=admin">Admin</a></li>
                  <li><a class="dropdown-item" href="?page=admin_profil_list" >Profiles List</a></li>
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                <?php endif; ?>
                <?php if (!isset($_SESSION['user'])) : ?>
                  <li><a class="dropdown-item" href="?page=login">Login</a></li>
                <?php else : ?>
                  <li><a class="dropdown-item" href="?page=logout">Logout</a></li>
                <?php endif; ?>
              </ul>
            </li>

        </ul>
            <form class="d-flex" role="search">
                <input name="page" value="search" type="hidden">
                <input name="keywords" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
</header>
<!-- MAIN -->
<main class="container-fluid">
<?= $template ?>
</main>
<!-- MODAL COOKIE -->
<div class="modal" tabindex="-1" id="modalCookie">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal COOKIE</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Acceptez-vous les cookies ?</p>
      </div>
      <div class="modal-footer">
        <form method="POST">
        <button type="submit" name="cookie_no" class="btn btn-danger">No</button>
        <button type="submit" name="cookie_yes" class="btn btn-success">Yes</button>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- FOOTER -->
<footer>
<footer id="footer" class="bg-dark text-white text-center p-3">
    <p> &copy; CCI BEAUJOLAIS - DWWM</p>
    <?php if(isset($_SESSION['cookie'])):?>
      <?php if((bool)$_SESSION['cookie']===true):?>
        Vous avez accepté les cookies<br>
        <?php else: ?>
        Vous n'avez pas accepté les cookies<br>
      <?php endif; ?>
    <a href="javascript:modalCookieShow()">Révoquer mon choix de cookie</a>
    <?php endif; ?>
</footer>
</footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  <script>
  const modalCookie = new bootstrap.Modal(document.getElementById('modalCookie'));
  <?php if (!isset($_SESSION['cookie'])) echo "modalCookie.show();"; ?>
  function modalCookieShow(){
    modalCookie.show();
  }
</script>
</body>
</html>